name: Play Music on GitHub Profile

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  play_music:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Play Sound
        uses: mxschmitt/play-sound-action@v1
        with:
          sound: 'https://github.com/pksenpai/pksenpai/blob/main/rule-of-life-brock-hewitt-stories-in-sound-main-version-29683-03-53.mp3'
