name: Play Music on GitHub Profile

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  play_music:
    runs-on: ubuntu-latest

    steps:
      - name: netease-music-box
        # You may pin to the exact commit or the version.
        # uses: SteveYurongSu/netease-music-box@a9c27709c6a680622f1fa79b9e0a28759367388b
        uses: SteveYurongSu/netease-music-box@v1.0
              
